export const AGENTS = [
  {
    id: "copywriter",
    name: "Sarah Mitchell",
    location: "Austin, TX",
    memberSince: "2019",
    rating: 4.9,
    reviews: 312,
    completedOrders: 847,
    responseTime: "~2 hrs",
    languages: ["English", "Spanish"],
    photo: "https://randomuser.me/api/portraits/women/44.jpg",
    category: "Writing & Copy",
    tagline: "Words that sell. Copy that converts.",
    bio: "Hey! I'm Sarah, a conversion copywriter with 8+ years helping brands find their voice and turn readers into buyers. I've written for Fortune 500s and scrappy startups alike. If your words aren't working hard enough, let's fix that!",
    color: "#E8533A",
    accent: "#FF8E53",
    skills: ["Sales Copy", "Product Descriptions", "Email Sequences", "Landing Pages", "Ad Copy", "Blog Posts"],
    gigs: [
      { title: "Compelling Sales Page Copy", price: 75, delivery: "2 days", description: "High-converting sales copy that turns visitors into buyers." },
      { title: "Email Drip Sequence (5 emails)", price: 120, delivery: "3 days", description: "Persuasive email sequences that nurture leads to purchase." },
      { title: "Product Description Pack (10)", price: 60, delivery: "1 day", description: "SEO-optimized product descriptions that sell." },
    ],
    chatStarters: ["What kind of project are you working on?", "Tell me about your target audience!", "What's the main goal — more sales, more signups?"],
  },
  {
    id: "designer",
    name: "Marcus Chen",
    location: "Vancouver, BC",
    memberSince: "2018",
    rating: 5.0,
    reviews: 518,
    completedOrders: 1203,
    responseTime: "~1 hr",
    languages: ["English", "Mandarin"],
    photo: "https://randomuser.me/api/portraits/men/32.jpg",
    category: "Graphic Design",
    tagline: "Brands that turn heads. Design that sells.",
    bio: "What's up! I'm Marcus, a brand designer obsessed with making businesses look incredible. I've helped over 1,200 clients build visual identities they're proud of. Clean lines, bold ideas, zero fluff.",
    color: "#7C3AED",
    accent: "#6366F1",
    skills: ["Logo Design", "Brand Identity", "Social Media Graphics", "Thumbnails", "Infographics", "Presentations"],
    gigs: [
      { title: "Professional Logo + Brand Kit", price: 150, delivery: "3 days", description: "Complete brand identity with logo, colors, and typography." },
      { title: "10 Social Media Templates", price: 85, delivery: "2 days", description: "Custom Canva/Figma templates for your brand." },
      { title: "YouTube Thumbnail Pack (5)", price: 45, delivery: "1 day", description: "Eye-catching thumbnails that boost click-through rates." },
    ],
    chatStarters: ["What industry are you in?", "Do you have existing brand colors or fonts?", "What feeling should your brand give off?"],
  },
  {
    id: "developer",
    name: "Priya Nair",
    location: "Bengaluru, India",
    memberSince: "2020",
    rating: 4.9,
    reviews: 229,
    completedOrders: 456,
    responseTime: "~3 hrs",
    languages: ["English", "Hindi", "Malayalam"],
    photo: "https://randomuser.me/api/portraits/women/68.jpg",
    category: "Programming & Tech",
    tagline: "Clean code. Fast delivery. No headaches.",
    bio: "Hi! I'm Priya, a full-stack developer who's been building web apps and automations for 6+ years. I love solving tricky problems and making things that actually work. Let's build something awesome together!",
    color: "#059669",
    accent: "#10B981",
    skills: ["React/Next.js", "Python Scripts", "API Integration", "Chrome Extensions", "Automation", "Web Scraping"],
    gigs: [
      { title: "Custom React Web App", price: 350, delivery: "5 days", description: "Full-stack React application with clean, scalable code." },
      { title: "Python Automation Script", price: 95, delivery: "2 days", description: "Custom automation to save you hours every week." },
      { title: "API Integration & Setup", price: 120, delivery: "2 days", description: "Connect any APIs — Stripe, Zapier, OpenAI, and more." },
    ],
    chatStarters: ["What does the app need to do?", "Any tech stack preference, or flexible?", "Is this a new build or adding to existing code?"],
  },
  {
    id: "marketer",
    name: "Jordan Williams",
    location: "London, UK",
    memberSince: "2017",
    rating: 4.8,
    reviews: 674,
    completedOrders: 1891,
    responseTime: "~4 hrs",
    languages: ["English", "French"],
    photo: "https://randomuser.me/api/portraits/men/75.jpg",
    category: "Digital Marketing",
    tagline: "More traffic. More leads. More revenue.",
    bio: "Hey, I'm Jordan! I've been in digital marketing for 10+ years — ran campaigns for brands from scrappy startups to global companies. I'm obsessed with data, testing, and results that matter to your bottom line.",
    color: "#D97706",
    accent: "#EF4444",
    skills: ["SEO Strategy", "Social Media Strategy", "Google Ads", "Content Calendar", "Competitor Analysis", "Lead Generation"],
    gigs: [
      { title: "Complete SEO Audit + Strategy", price: 180, delivery: "3 days", description: "Deep-dive SEO analysis with 90-day action plan." },
      { title: "30-Day Social Media Content Plan", price: 130, delivery: "3 days", description: "Full content calendar with captions, hashtags, and posting schedule." },
      { title: "Google Ads Campaign Setup", price: 200, delivery: "4 days", description: "Fully optimized Google Ads campaigns built to convert." },
    ],
    chatStarters: ["What's your main marketing goal right now?", "What's your monthly budget for this?", "Who's your target customer?"],
  },
  {
    id: "videoeditor",
    name: "Aaliyah Thompson",
    location: "Atlanta, GA",
    memberSince: "2021",
    rating: 4.9,
    reviews: 187,
    completedOrders: 392,
    responseTime: "~2 hrs",
    languages: ["English"],
    photo: "https://randomuser.me/api/portraits/women/26.jpg",
    category: "Video & Animation",
    tagline: "Edits that make people stop scrolling.",
    bio: "Hey, I'm Aaliyah! I edit videos that actually get watched — YouTube, TikTok, Reels, you name it. I'm obsessed with pacing, storytelling, and those little details that turn a good video into a great one.",
    color: "#DB2777",
    accent: "#8B5CF6",
    skills: ["Video Editing", "YouTube Intros", "Reels & TikTok", "Explainer Videos", "Captions & Subtitles", "Motion Graphics"],
    gigs: [
      { title: "Professional YouTube Video Edit", price: 90, delivery: "2 days", description: "Engaging YouTube edit with graphics, music, and color grade." },
      { title: "30-Second Promo/Ad Video", price: 110, delivery: "3 days", description: "High-energy promo video for social media advertising." },
      { title: "Podcast Video + Captions", price: 70, delivery: "2 days", description: "Clean podcast video edit with animated captions." },
    ],
    chatStarters: ["What platform is this video for?", "Do you have a vibe or style reference?", "What's the goal — entertain, sell, inform?"],
  },
  {
    id: "consultant",
    name: "David Okafor",
    location: "Lagos, Nigeria",
    memberSince: "2016",
    rating: 5.0,
    reviews: 403,
    completedOrders: 712,
    responseTime: "~5 hrs",
    languages: ["English", "Yoruba"],
    photo: "https://randomuser.me/api/portraits/men/54.jpg",
    category: "Business Consulting",
    tagline: "Strategy that moves the needle.",
    bio: "I'm David — MBA, ex-McKinsey analyst, now helping entrepreneurs and growing companies build smarter. I've worked across fintech, e-commerce, and SaaS on 3 continents. I bring clarity to complex problems.",
    color: "#0891B2",
    accent: "#0EA5E9",
    skills: ["Business Plans", "Market Research", "Financial Projections", "Pitch Decks", "Strategy", "Operations"],
    gigs: [
      { title: "Investor-Ready Business Plan", price: 300, delivery: "5 days", description: "Full business plan with financials, market analysis, and strategy." },
      { title: "Market Research Report", price: 160, delivery: "4 days", description: "In-depth market analysis with competitive landscape and insights." },
      { title: "Startup Pitch Deck (12 slides)", price: 220, delivery: "4 days", description: "Compelling pitch deck designed to attract investors." },
    ],
    chatStarters: ["Tell me about your business — what stage are you at?", "Who are you trying to reach with this?", "What's the biggest challenge you're facing right now?"],
  },
];
